### PR TITLE
Remote project fix

### PR DESCRIPTION
**Pull request by leobastiani**

### CODE REVIEW

**Comment by leobastiani** [comment]
i'm using docker with hhvm on windows
i have to change remote docker projects path to my local project

**Comment by leobastiani** [comment]
thats is working

**Comment by martomo** [comment]
How is this different from the existing `path_mapping` setting available in [configuration](https://github.com/martomo/SublimeTextXdebug#configuration)?

**Comment by leobastiani** [comment]
i'm sorry, i didn't realize that configuration, they are the same thing

**Pull request closed without merging**
