### PR TITLE
Fix quote parsing on XML

### PR DESCRIPTION
**Pull request by gepeixoto**
This fix an error while parsing quotes in XML returned from Xdebug server

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@martomo, can this get merged/released?

**Comment by ryanpcmcquen** [comment]
@gepeixoto, have you considered merging in all PRs and making your own version for Package Control?

**Comment by ryanpcmcquen** [comment]
I've merged your fixes into my fork:
https://github.com/ryanpcmcquen/SublimeTextXdebugPlus

Which I am attempting to get into Package Control:
https://github.com/wbond/package_control_channel/pull/7658

**Comment by martomo** [comment]
@gepeixoto Thanks for contributing, I've added an exception for quote (and apostrophe) entities in 0b76fe7438bd01cf18469cafdb8032594252fc1b, as alternative to your proposed solution which would actually change `&quot` (`"`) incorrectly as `'`(`&apos`) that resulted in different rendered output from Xdebug response.

**Pull request closed without merging**
